name: build

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        python-version: [ "3.8", "3.9" ]

    steps:
      - uses: actions/checkout@v2.4.0

      - name: Build stack
        run: docker-compose build
